[profile.default]
src = "src"
out = "out"
libs = ["lib"]


# Essential for OpenZeppelin upgrades
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
build_info = true
extra_output = ["storageLayout"]

# Metadata configuration for upgrades
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code
ast = true

# Monad Configuration
eth_rpc_url = "https://testnet-rpc.monad.xyz"
chain_id = 10143

